# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' r_categ_mat
#' 
#' Sample from a matrix of categorical probabilities.
#' 
#' @param prob An \eqn{n \times k} matrix of probabilities, where \eqn{k} is
#' the number of categories and \eqn{n} is the desired number of indepedent
#' draws.
#' 
#' @returns a vector of category zero-based indices whose elements are in
#' \eqn{0, \ldots, k-1}.
#' 
#' @details
#' It might be more useful to have a version of this function that takes
#' probabilities on the log-scale. We could consider using the Gumbel trick
#' for that.
#' 
#' @export
r_categ_mat <- function(prob) {
    .Call('_raim_r_categ_mat', PACKAGE = 'raim', prob)
}

